# 1. Импорт библиотек

In [1]:
import pandas as pd
import requests, json
import time

# 2. Подготовка списков марок и моделей

In [2]:
# Загрузим файл с перечнем марок автомобилей
with open('dict_mark.json', 'r', encoding='utf-8') as f: 
    dict_mark = json.load(f)

In [3]:
dict_mark

{'AC': '3',
 'AMC': '2',
 'Acura': '63',
 'Alfa Romeo': '39',
 'Alpina': '2',
 'Ariel': '1',
 'Aro': '1',
 'Asia': '1',
 'Aston Martin': '14',
 'Audi': '3484',
 'Austin Healey': '1',
 'BMW': '5815',
 'BYD': '10',
 'Bentley': '82',
 'Borgward': '1',
 'Brilliance': '11',
 'Buick': '9',
 'CHERYEXEED': '5',
 'Cadillac': '324',
 'Changan': '180',
 'Chery': '604',
 'Chevrolet': '2323',
 'Chrysler': '212',
 'Citroen': '871',
 'DKW': '2',
 'DS': '1',
 'DW Hower': '5',
 'Dacia': '7',
 'Daewoo': '559',
 'Daihatsu': '32',
 'Daimler': '3',
 'Dallara': '1',
 'Datsun': '134',
 'Delage': '1',
 'Derways': '1',
 'Dodge': '299',
 'DongFeng': '12',
 'Doninvest': '2',
 'Eagle': '2',
 'Excalibur': '1',
 'FAW': '48',
 'Ferrari': '29',
 'Fiat': '167',
 'Ford': '2934',
 'GAC': '2',
 'GMC': '19',
 'Geely': '290',
 'Genesis': '38',
 'Great Wall': '305',
 'Hafei': '2',
 'Haima': '8',
 'Haval': '460',
 'Hawtai': '3',
 'Heinkel': '1',
 'Honda': '769',
 'Hummer': '43',
 'Hyundai': '4672',
 'Infiniti': '649',
 'Iran Khodro': '15',
 'Isuzu': '24',
 'JAC': '6',
 'Jaguar': '263',
 'Jeep': '453',
 'Kia': '5257',
 'LADA (ВАЗ)': '6743',
 'Lamborghini': '11',
 'Lancia': '7',
 'Land Rover': '1286',
 'Lexus': '950',
 'Lifan': '172',
 'Lincoln': '53',
 'Luxgen': '11',
 'MG': '4',
 'MINI': '518',
 'Maserati': '43',
 'Maybach': '6',
 'Mazda': '1745',
 'McLaren': '1',
 'Mercedes-Benz': '9900',
 'Mercury': '9',
 'Metrocab': '1',
 'Mitsubishi': '3158',
 'Mitsuoka': '1',
 'Nissan': '5146',
 'Oldsmobile': '6',
 'Opel': '2048',
 'PUCH': '1',
 'Packard': '2',
 'Peugeot': '1130',
 'Plymouth': '12',
 'Pontiac': '19',
 'Porsche': '613',
 'Proton': '1',
 'RAM': '9',
 'Ravon': '75',
 'Renault': '4042',
 'Rolls-Royce': '63',
 'Rover': '44',
 'SEAT': '65',
 'Saab': '105',
 'Saturn': '4',
 'Scion': '5',
 'Shanghai Maple': '1',
 'Skoda': '3131',
 'Smart': '70',
 'SsangYong': '449',
 'Subaru': '593',
 'Suzuki': '857',
 'Tatra': '1',
 'Tesla': '47',
 'Toyota': '2976',
 'Triumph': '1',
 'Volkswagen': '5394',
 'Volvo': '1449',
 'Vortex': '50',
 'Willys': '2',
 'Xin Kai': '1',
 'ZX': '4',
 'Zotye': '12',
 'ГАЗ': '736',
 'Гоночный автомобиль': '3',
 'ЗАЗ': '179',
 'ЗИЛ': '3',
 'ЗиС': '1',
 'ИЖ': '101',
 'ЛуАЗ': '36',
 'Москвич': '165',
 'СМЗ': '3',
 'ТагАЗ': '53',
 'УАЗ': '873'}

In [4]:
# Удалим не популярные модели с количеством объявлений ниже 300
keys_to_delete = []
for mark in dict_mark.keys():
    if int(dict_mark[mark]) < 300:
        keys_to_delete.append(mark)
    
for key in keys_to_delete: del dict_mark[key]

In [5]:
# Удалим модели с русскими названиями
for key in ['LADA (ВАЗ)','ГАЗ','УАЗ']: del dict_mark[key]

In [6]:
# Приведем к единому регистру
for mark in list(dict_mark.keys()):
    mark_up = mark.upper()
    dict_mark[mark_up]=dict_mark.pop(mark)

In [7]:
# При загрузке в адресной строке сложные названия марок представляются иначе. Приведем к единому виду
dict_mark['MERCEDES']=dict_mark.pop('MERCEDES-BENZ')
dict_mark['LAND_ROVER']=dict_mark.pop('LAND ROVER')
dict_mark['GREAT_WALL']=dict_mark.pop('GREAT WALL')
dict_mark['SSANG_YONG']=dict_mark.pop('SSANGYONG')

In [8]:
print(*dict_mark, sep = '  ,  ')

AUDI  ,  BMW  ,  CADILLAC  ,  CHERY  ,  CHEVROLET  ,  CITROEN  ,  DAEWOO  ,  FORD  ,  HAVAL  ,  HONDA  ,  HYUNDAI  ,  INFINITI  ,  JEEP  ,  KIA  ,  LEXUS  ,  MINI  ,  MAZDA  ,  MITSUBISHI  ,  NISSAN  ,  OPEL  ,  PEUGEOT  ,  PORSCHE  ,  RENAULT  ,  SKODA  ,  SUBARU  ,  SUZUKI  ,  TOYOTA  ,  VOLKSWAGEN  ,  VOLVO  ,  MERCEDES  ,  LAND_ROVER  ,  GREAT_WALL  ,  SSANG_YONG

In [9]:
# Список марок для парсинга
list_of_marks = list(dict_mark.keys())

In [10]:
# Загрузим файл моделей автомобилей
df_models = pd.read_csv('marks_and_models_from_auto_ru.csv', index_col=0)

In [11]:
df_models.sample(10)

                                                     Models
Mark
CATERHAM                            ['C21', 'CSR', 'SEVEN']
KOMBAT                                              ['T98']
GORDON                                         ['ROADSTER']
PGO                  ['CEVENNES', 'HEMERA', 'SPEEDSTER_II']
NOBLE                            ['M12_GTO', 'M15', 'M600']
ALPINA    ['B10', 'B11', 'B12', 'B3', 'B4', 'B5', 'B6', ...
CHERY     ['AMULET', 'ARRIZO_3', 'ARRIZO7', 'B13', 'BONU...
FUQI                                          ['LAND_KING']
ZENOS                                               ['E10']
LIEBAO                                          ['LEOPARD']

# 3. Подготовка к парсингу

In [12]:
# Загрузим test и посмотрим какие столбцы нам нужны 
test = pd.read_csv('test.csv')
print('Кол-во столбцов теста:', test.shape[1])
print('Названия столбцов теста:', list(test.columns))

# вывод всех столбцов датафрейма
pd.set_option('display.max_columns', None)
test.sample(2)

Кол-во столбцов теста: 32
Названия столбцов теста: ['bodyType', 'brand', 'car_url', 'color', 'complectation_dict', 'description', 'engineDisplacement', 'enginePower', 'equipment_dict', 'fuelType', 'image', 'mileage', 'modelDate', 'model_info', 'model_name', 'name', 'numberOfDoors', 'parsing_unixtime', 'priceCurrency', 'productionDate', 'sell_id', 'super_gen', 'vehicleConfiguration', 'vehicleTransmission', 'vendor', 'Владельцы', 'Владение', 'ПТС', 'Привод', 'Руль', 'Состояние', 'Таможня']

,bodyType,brand,car_url,color,complectation_dict,description,engineDisplacement,enginePower,equipment_dict,fuelType,image,mileage,modelDate,model_info,model_name,name,numberOfDoors,parsing_unixtime,priceCurrency,productionDate,sell_id,super_gen,vehicleConfiguration,vehicleTransmission,vendor,Владельцы,Владение,ПТС,Привод,Руль,Состояние,Таможня
26061,хэтчбек 5 дв.,VOLKSWAGEN,https://auto.ru/cars/used/sale/volkswagen/golf...,серебристый,NaN,.\nВ КорсАвто сезонная распродажа! Не упустите...,1.2 LTR,105 N12,"{""collision-prevention-assist"":true,""computer""...",бензин,https://avatars.mds.yandex.net/get-autoru-vos/...,140180,2008,"{""code"":""GOLF"",""name"":""Golf"",""ru_name"":""Гольф""...",GOLF,1.2 AMT (105 л.с.),5,1603223729,RUB,2011,1100903504,"{""id"":""6298295"",""displacement"":1197,""engine_ty...",HATCHBACK_5_DOORS ROBOT 1.2,роботизированная,EUROPEAN,1 владелец,NaN,Оригинал,передний,Левый,Не требует ремонта,Растаможен
32088,компактвэн,HONDA,https://auto.ru/cars/used/sale/honda/freed/110...,чёрный,NaN,Продаю. Хонда фрид спайк авто в отличном состо...,1.5 LTR,118 N12,"{""engine-proof"":true,""cruise-control"":true,""es...",бензин,https://autoru.naydex.net/1xsMU7627/eea2057RFg...,57000,2008,"{""code"":""FREED"",""name"":""Freed"",""ru_name"":""Фрид...",FREED,Spike 1.5 CVT (118 л.с.),5,1603595622,RUB,2012,1101344619,"{""id"":""20495326"",""name"":""Spike"",""nameplate"":""S...",COMPACTVAN VARIATOR 1.5,вариатор,JAPANESE,1 владелец,NaN,Оригинал,передний,Правый,Не требует ремонта,Растаможен

In [13]:
# Функция для очистки временного словаря
def clean_info_values(car_info):
    for value in car_info:
        car_info[value] = 0

In [14]:
# Функция для сбора словаря данных для одной машины
def from_car_info_to_dict(car_in_data, car_info):
    clean_info_values(car_info)

    try:
        car_info['bodyType'] = car_in_data['vehicle_info']['configuration']['human_name']
    except:
        car_info['bodyType'] = None

    try:
        car_info['brand'] = car_in_data['vehicle_info']['mark_info']['code']
    except:
        car_info['brand'] = None

    try:
        car_info['color'] = car_in_data['color_hex']
    except:
        car_info['color'] = None

    try:
        car_info['complectation_dict'] = car_in_data['vehicle_info']['complectation']
    except:
        car_info['complectation_dict'] = None

    try:
        car_info['description'] = car_in_data['description']
    except:
        car_info['description'] = None

    try:
        car_info['engineDisplacement'] = car_in_data['vehicle_info']['tech_param']['human_name'].split()[
            0]
    except:
        car_info['engineDisplacement'] = None

    try:
        car_info['enginePower'] = car_in_data['vehicle_info']['tech_param']['power']
    except:
        car_info['enginePower'] = None

    try:
        car_info['equipment_dict'] = car_in_data['vehicle_info']['equipment']
    except:
        car_info['equipment_dict'] = None

    try:
        car_info['fuelType'] = car_in_data['lk_summary'].split()[-1]
    except:
        car_info['fuelType'] = None

    try:
        car_info['image'] = car_in_data['state']['image_urls'][0]['sizes']['320x240']
    except:
        car_info['image'] = None

    try:
        car_info['mileage'] = car_in_data['state']['mileage']
    except:
        car_info['mileage'] = None

    try:
        car_info['modelDate'] = car_in_data['vehicle_info']['super_gen']['year_from']
    except:
        car_info['modelDate'] = None

    try:
        car_info['model_info'] = car_in_data['vehicle_info']['model_info']
    except:
        car_info['model_info'] = None

    try:
        car_info['model_name'] = car_in_data['vehicle_info']['model_info']['code']
    except:
        car_info['model_name'] = None

    try:
        car_info['name'] = car_in_data['vehicle_info']['tech_param']['human_name']
    except:
        car_info['name'] = None

    try:
        car_info['numberOfDoors'] = car_in_data['vehicle_info']['configuration']['doors_count']
    except:
        car_info['numberOfDoors'] = None

    try:
        car_info['priceCurrency'] = car_in_data['price_info']['currency']
    except:
        car_info['priceCurrency'] = None

    try:
        car_info['productionDate'] = car_in_data['documents']['year']
    except:
        car_info['productionDate'] = None

    try:
        car_info['sell_id'] = car_in_data['id']
    except:
        car_info['sell_id'] = None

    try:
        car_info['super_gen'] = car_in_data['vehicle_info']['tech_param']
    except:
        car_info['super_gen'] = None

    try:
        car_info['vehicleConfiguration'] = car_in_data['vehicle_info']['configuration']['body_type']+' ' + \
            car_in_data['vehicle_info']['tech_param']['transmission']+' ' + \
            car_in_data['vehicle_info']['tech_param']['human_name'].split()[0]
    except:
        car_info['vehicleConfiguration'] = None

    try:
        car_info['vehicleTransmission'] = car_in_data['vehicle_info']['tech_param']['transmission']
    except:
        car_info['vehicleTransmission'] = None

    try:
        car_info['vendor'] = car_in_data['vehicle_info']['vendor']
    except:
        car_info['vendor'] = None

    try:
        car_info['Владельцы'] = car_in_data['documents']['owners_number']
    except:
        car_info['Владельцы'] = None

    try:
        car_info['Владение'] = car_in_data['documents']['purchase_date']
    except:
        car_info['Владение'] = None

    try:
        car_info['ПТС'] = car_in_data['documents']['pts']
    except:
        car_info['ПТС'] = None

    try:
        car_info['Привод'] = car_in_data['lk_summary'].split(', ')[-2]
    except:
        car_info['Привод'] = None

    try:
        car_info['Руль'] = car_in_data['vehicle_info']['steering_wheel']
    except:
        car_info['Руль'] = None

    try:
        car_info['Состояние'] = car_in_data['status'] == 'ACTIVE'
    except:
        car_info['Состояние'] = None

    try:
        car_info['Таможня'] = car_in_data['documents']['custom_cleared']
    except:
        car_info['Таможня'] = None

    try:
        car_info['tax_by_year'] = car_in_data['owner_expenses']['transport_tax']['tax_by_year']
    except:
        car_info['tax_by_year'] = None

    try:
        car_info['transport_tax_rid'] = car_in_data['owner_expenses']['transport_tax']['rid']
    except:
        car_info['transport_tax_rid'] = None

    try:
        car_info['insurance_company'] = car_in_data['owner_expenses']['osago_insurance'][0]['insurance_company']
    except:
        car_info['insurance_company'] = None

    try:
        car_info['osago_insurance_price'] = car_in_data['owner_expenses']['osago_insurance'][0]['price']
    except:
        car_info['osago_insurance_price'] = None

    try:
        car_info['start_date'] = car_in_data['additional_info']['hot_info']['start_time']
    except:
        car_info['start_date'] = None

    try:
        car_info['auto_class'] = car_in_data['vehicle_info']['configuration']['auto_class']
    except:
        car_info['auto_class'] = None

    try:
        car_info['price_RUR'] = car_in_data['price_info']['RUR']
    except:
        car_info['price_RUR'] = None

    try:
        car_info['price_EUR'] = car_in_data['price_info']['EUR']
    except:
        car_info['price_EUR'] = None

    try:
        car_info['price_USD'] = car_in_data['price_info']['USD']
    except:
        car_info['price_USD'] = None

    return car_info

# 4. Парсинг

In [15]:
# Словарь для сбора данных по одной машине
colums_dict = {'bodyType': 0, 'brand': 0, 'color': 0, 'complectation_dict': 0,
               'description': 0, 'engineDisplacement': 0, 'enginePower': 0, 
               'equipment_dict': 0, 'fuelType': 0, 'image': 0, 'mileage': 0, 'modelDate': 0,
               'model_info': 0, 'model_name': 0, 'name': 0, 'numberOfDoors': 0, 
               'priceCurrency': 0, 'productionDate': 0, 'sell_id': 0,
               'super_gen': 0, 'vehicleConfiguration': 0, 'vehicleTransmission': 0,
               'vendor': 0, 'Владельцы': 0, 'Владение': 0, 'ПТС': 0, 'Привод': 0, 'Руль': 0,
               'Состояние': 0, 'Таможня': 0, 'tax_by_year': 0, 'transport_tax_rid': 0, 
               'insurance_company': 0, 'osago_insurance_price': 0, 'start_date': 0, 'auto_class': 0, 
               'price_RUR': 0, 'price_EUR': 0, 'price_USD': 0}

In [16]:
# url для парсинга auto.ru
url = "https://auto.ru/-/ajax/desktop/listing/"

In [17]:
HEADERS = {
    'Accept': '*/*',
    'Accept-Encoding': 'gzip, deflate, br',
    'Connection': 'keep-alive',
    'Content-Length': '<calculated when request is sent>',
    'content-type': 'application/json',
    'Cookie': '_csrf_token=69292abc547f3cfabac9d3d454b678c67f6471d398451743',
    'Host': 'auto.ru',
    'x-csrf-token': '69292abc547f3cfabac9d3d454b678c67f6471d398451743',
}

In [18]:
auto_ru = {}  # итоговый словарь для записи
iteration = 0

for mark in list_of_marks:

    list_of_models = json.loads(
        df_models.loc[mark, 'Models'].replace("'", '"'))

    for model in list_of_models:

        for num_page in range(1, 200):

            param = {
                "catalog_filter": [{"mark": mark, "model": model}],
                "section": "all",
                "category": "cars",
                "sort": "fresh_relevance_1-desc",
                "top_days": 900,
                "geo_radius": 200,
                "geo_id": [213],
                "page": num_page
            }

            # Из-за превышения времени ожидания ответа цикл может обрываться.
            # Исключим прерывания блоком try-except

            attempt = 1    # подсчет количества попыток

            while attempt < 4:

                try:
                    response = requests.post(url, json=param, headers=HEADERS)
                    data = response.json()
                    break

                except:
                    attempt += 1
                    print(
                        f'Марка: {mark}. Модель: {model}. Страница: {num_page}.')
                    print(
                        f'Время ожидания ответа превышено. {attempt}-я попытка')
                    time.sleep(1)

            if data['offers'] != []:
                for car in data['offers']:
                    from_car_info_to_dict(car, colums_dict)
                    auto_ru[iteration] = colums_dict.copy()
                    iteration += 1

            else:
                break
print('Готово!')

Марка: VOLKSWAGEN. Модель: TOUAREG. Страница: 9.
Время ожидания ответа превышено. 2-я попытка
Готово!

In [20]:
# Представим собранный словарь в виде датасета
df_auto_ru = pd.DataFrame(auto_ru).T
df_auto_ru.sample(5)

,bodyType,brand,color,complectation_dict,description,engineDisplacement,enginePower,equipment_dict,fuelType,image,mileage,modelDate,model_info,model_name,name,numberOfDoors,priceCurrency,productionDate,sell_id,super_gen,vehicleConfiguration,vehicleTransmission,vendor,Владельцы,Владение,ПТС,Привод,Руль,Состояние,Таможня,tax_by_year,transport_tax_rid,insurance_company,osago_insurance_price,start_date,auto_class,price_RUR,price_EUR,price_USD
66079,Седан,MERCEDES,FAFBFB,{'id': '0'},"Богатая комплектация, состояние нового автомоб...",220,194,"{'asr': True, 'tinted-glass': True, 'roller-bl...",дизель,//avatars.mds.yandex.net/get-autoru-vos/205847...,43000,2016,"{'code': 'E_KLASSE', 'name': 'E-Класс', 'ru_na...",E_KLASSE,220 d 2.0d AT (194 л.с.),4,RUR,2016,1101237713,"{'id': '20743601', 'name': '220', 'nameplate':...",SEDAN AUTOMATIC 220,AUTOMATIC,EUROPEAN,2,"{'year': 2017, 'month': 2}",ORIGINAL,задний,LEFT,True,True,9700,213,TINKOFF,6309,2020-10-13T11:16:12Z,E,2800000,30839,38033
44205,Седан,PEUGEOT,0000CC,{'id': '0'},РОЛЬФ Северо-Запад - это первый мегамолл автом...,1.6,120,{'fabric-seats': True},бензин,//avatars.mds.yandex.net/get-autoru-vos/163354...,102433,2012,"{'code': '408', 'name': '408', 'ru_name': '408...",408,1.6 AT (120 л.с.),4,RUR,2015,1101638040,"{'id': '8350885', 'displacement': 1598, 'engin...",SEDAN AUTOMATIC 1.6,AUTOMATIC,EUROPEAN,2,None,ORIGINAL,передний,LEFT,True,True,3000,213,TINKOFF,4732,2020-11-19T13:18:05Z,C,535000,5893,7267
39491,Внедорожник 5 дв.,NISSAN,040001,{'id': '0'},Состояние нового авто. Без аварий. Кондиционер...,2.0,135,"{'engine-proof': True, 'esp': True, 'front-cen...",бензин,//avatars.mds.yandex.net/get-autoru-vos/204856...,4477,2014,"{'code': 'TERRANO', 'name': 'Terrano', 'ru_nam...",TERRANO,2.0 AT (135 л.с.),5,RUR,2015,1102023013,"{'id': '20145597', 'displacement': 1998, 'engi...",ALLROAD_5_DOORS AUTOMATIC 2.0,AUTOMATIC,JAPANESE,1,None,ORIGINAL,передний,LEFT,True,True,4725,213,TINKOFF,5521,2020-12-26T12:08:35Z,J,790000,8701,10731
33873,Седан,MITSUBISHI,0000CC,{'id': '0'},"Лансерок в хорошем состояние, чистый непрокуре...",2.0,150,"{'engine-proof': True, 'tinted-glass': True, '...",бензин,//avatars.mds.yandex.net/get-autoru-vos/421943...,105000,2007,"{'code': 'LANCER', 'name': 'Lancer', 'ru_name'...",LANCER,2.0 MT (150 л.с.),4,RUR,2008,1101764929,"{'id': '20395161', 'displacement': 1998, 'engi...",SEDAN MECHANICAL 2.0,MECHANICAL,JAPANESE,3,None,ORIGINAL,передний,LEFT,True,True,4500,10658,TINKOFF,4416,2020-12-02T06:34:39Z,C,410000,4516,5569
44371,Седан,PEUGEOT,0000CC,{'id': '0'},Продаю надёжный и комфортный автомобиль.Причин...,3.0,207,"{'cruise-control': True, 'asr': True, 'roller-...",бензин,//avatars.mds.yandex.net/get-autoru-vos/391359...,193000,2000,"{'code': '607', 'name': '607', 'ru_name': '607...",607,3.0 AT (207 л.с.),4,RUR,2004,1101957935,"{'id': '6331277', 'displacement': 2946, 'engin...",SEDAN AUTOMATIC 3.0,AUTOMATIC,EUROPEAN,3,None,ORIGINAL,передний,LEFT,True,True,13455,213,TINKOFF,6309,2020-12-20T11:21:57Z,E,300000,3304,4075

In [21]:
# Размер собранного датасета
df_auto_ru.shape

(75441, 39)

In [22]:
# Запись датасета в файл
df_auto_ru.to_csv('auto_ru_06_01_2021.csv', index=False)